#pragma once
#include <vector>
#include <string>

namespace rfxh::logo::builtin::cat_linux {

inline std::vector<std::string> logo_Peppermint() {
    return {
        "             PPPPPPPPPPPPPP",
        "         PPPPMMMMMMMPPPPPPPPPPP",
        "       PPPPMMMMMMMMMMPPPPPPPPMMPP",
        "     PPPPPPPPMMMMMMMPPPPPPPPMMMMMPP",
        "   PPPPPPPPPPPPMMMMMMPPPPPPPMMMMMMMPP",
        "  PPPPPPPPPPPPMMMMMMMPPPPMPMMMMMMMMMPP",
        " PPMMMMPPPPPPPPPPMMMPPPPPMMMMMMMPMMPPPP",
        " PMMMMMMMMMMPPPPPPMMPPPPPMMMMMMPPPPPPPP",
        "PMMMMMMMMMMMMPPPPPMMPPMPMMPMMPPPPPPPPPPP",
        "PMMMMMMMMMMMMMMMMPPMPMMMPPPPPPPPPPPPPPPP",
        "PMMMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMP",
        "PPPPPPPPPPPPPPPPMMMPMPMMMMMMMMMMMMMMMMPP",
        "PPPPPPPPPPPMMPMMPPPPMMPPPPPMMMMMMMMMMMPP",
        " PPPPPPPPMMMMMMPPPPPMMPPPPPPMMMMMMMMMPP",
        " PPPPMMPMMMMMMMPPPPPPMMPPPPPPPPPPMMMMPP",
        "  PPMMMMMMMMMPMPPPPMMMMMMPPPPPPPPPPPPP",
        "   PPMMMMMMMPPPPPPPMMMMMMPPPPPPPPPPPP",
        "     PPMMMMPPPPPPPPPMMMMMMMPPPPPPPP",
        "       PPMMPPPPPPPPMMMMMMMMMMPPPP",
        "         PPPPPPPPPPMMMMMMMMPPPP",
        "             PPPPPPPPPPPPPP",
    };
}

}
