#pragma once
#include <vector>
#include <string>

namespace rfxh::logo::builtin::cat_linux {

inline std::vector<std::string> logo_Ultramarine() {
    return {
        "            .cd0NNNNNNNXOdc.",
        "        .:xKNNNNNNNNNNNNNNNNKd;.",
        "      ,dXNNNNNNNNNNNNNNNNNNNNNNNd,",
        "    'ONNNNNNNNNNNNNNNNNNNNNNNNNNNNO'",
        "  .xNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk.",
        " .0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0.",
        ".0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0.",
        "dNNNNNNNNNNNNWWWWWWWWNNNNNNNNNNNNNNNNNNd",
        "NNNNNNNNNNNNNWMMMMMMMMWWNNNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNWMMMMMMMMMWWNNNNNNNNNNNNNN",
        "NNNNNNNNNNNNNNWMMMMMMMMMMMMWNNNNNNNNNNNN",
        "NNNNNNNNNNWWWMMMMMMMMMMMMMMMMWWWNNNNNNNX",
        "oNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNo",
        " OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO",
        " .OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO.",
        "   lNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNl",
        "    .dNWMMMMMMMMMMMMMMMMMMMMMMMMWNd.",
        "      .cKWMMMMMMMMMMMMMMMMMMMMWKc.",
        "         'oOXWWWMMMMMMMMWWWXOl.",
        "             ;lkXNNNNNNXkl'",
    };
}

}
